### ISSUE TITLE
Add vTPM support for TPM 2.0 (with KVM/QEMU)

### ISSUE THREAD

**Issue by jetwhiz** [mit-ll/python-keylime#29]
Currently Keylime works for vTPM with a TPM 1.2 (particularly in Xen).  Add support for TPM 2.0 and KVM/QEMU.

**Comment by lukehinds** [comment]
Some of my findings:

* [vTPM support in OpenStack Nova](https://specs.openstack.org/openstack/nova-specs/specs/stein/approved/add-emulated-virtual-tpm.html)

* [QEMU Spec](https://github.com/qemu/qemu/blob/master/docs/specs/tpm.txt)

* [Libvirt tpm xml elements](https://libvirt.org/formatdomain.html#elementsTpm)

* [script to compile / install Compile libtpms & swtpm on Fedora 29](https://gist.githubusercontent.com/lukehinds/952cee9bae8599b1b051970cafbfa51b/raw/e589a4d968af54539b78a104a2b82641a6c3bec8/vtpm.sh) - Note, will look into packaging this into Fedora.

**Comment by lukehinds** [comment]
I will start a draft PR for us to start scoping out this work.

**Comment by nabilschear** [comment]
it would be great if you can extend your setup script above to instantiate a basic fedora vm with a vtpm attached and a working set of tpm2-tools running in the vm.

**Comment by nabilschear** [comment]
PS: from a quick look at your research above this looks to have matured substantially from the last time i looked at it.  That's really encouraging.  The biggest challenge with all of this is to get machines with working vtpms.  The keylime part of it and how it uses it is all built already with xen.  So, we know how it should work, what interfaces are needed etc.  It should be straight-forward to port over to kvm/qemu

**Comment by lukehinds** [comment]
@nabilschear 

That's good to know.

> it would be great if you can extend your setup script above to instantiate a basic fedora vm with a vtpm attached and a working set of tpm2-tools running in the vm

Np!, I plan to do that anyway. Next week my task will be getting it working by hand, I will then use those findings to port into a script to automate this. Most likely some in python so we can use the libvirt library.

Thinking about this, it will most likely be the cloud orchestrator who will ultimately look after instantiating a VM with the vTPM (like with the above link to the OpenStack Nova spec), but we will make their life easier with code snippets and details on how to set this up and need something for bringing up a VM and vTPM for gate testing.

**Comment by nabilschear** [comment]
agreed.  the cloud orchestrator will also be responsible for setting up some keylime services so that their tenants can use vtpm.  i can walk through this when we're ready.

**Comment by lukehinds** [comment]
Good news, I have this working in a VM

```
[root@localhost ~]# dmesg | grep tpm
[    0.698078] tpm_tis 00:05: 2.0 TPM (device-id 0x1, rev-id 1)
[root@localhost ~]# ls -al /dev/tpm0 
crw-------. 1 root root 10, 224 Feb 21 15:05 /dev/tpm0
[root@localhost ~]# tpm2_getrandom 8
0x9C 0xB6 0x79 0x72 0xF0 0x3E 0x6D 0xBC
```

Just need to work out how to script this, as I needed to edit the libvirt xml by hand.

**Comment by lukehinds** [comment]
@nabilschear and here is a script to deploy this. I have not had a chance to test is a great deal, but you should be able to pick out the steps manually if need be:

https://gist.github.com/lukehinds/9fcee6fdc451d44116086b13b6125db9

**Comment by nabilschear** [comment]
I had to add `--allowerasing` to the dnf command to get all the packages in on my default build of fedora 29.  the rest is still building

**Comment by nabilschear** [comment]
still working on getting it working.   probably our web proxy is causing trouble.

**Comment by lukehinds** [comment]
@nabilschear how are you getting on ? Let me know if you need some help, I am back online now after a machine rebuild

**Comment by nabilschear** [comment]
i was doing it on my laptop with a slow connection.  So i never quite finished debugging it.  I'll try again later today and let you know if i get it working.

**Comment by nabilschear** [comment]
on this command in the gist you provided: `virt-install --ram 2048 --vcpus 2 --os-variant rhel7 \
    --disk path=/var/lib/libvirt/images/${vm_name}.qcow2,device=disk,bus=virtio,format=qcow2 \
    --import --noautoconsole --vnc --tpm /tmp/tpm0 \
    --network network:default --name ${vm_name}` it fails and says that `/tmp/tpm0` is not found.  does this need to be a file or socket that points to a running swtpm instance?

**Comment by nabilschear** [comment]
when i create an empty file for /tmp/tpm0 it then says something about passthrough not available.  note that i'm doing this in vmware on a mac with no actual tpm

**Comment by lukehinds** [comment]
This may well be due to vmware not supporting 'nested virtualization' - which version do you have? VMWare player?

Another possibility is to install Virtualbox which as of version 6.0 supports nested virt:

https://blogs.oracle.com/virtualization/oracle-vm-virtualbox-60-now-available

> Support for Nested Virtualization: This release adds support for nested virtualization on certain hardware platforms that enables you to install a hypervisor, such as Oracle VM VirtualBox, Oracle VM Server or KVM, on an Oracle VM VirtualBox guest. You can then create and run virtual machines in the guest VM. Support for nested virtualization allows VirtualBox to create a more flexible and sophisticated development and testing environment.

I will also see if I can get you a box somewhere and set it up for you.

**Comment by nabilschear** [comment]
i'll give it a try with virtual box.  Though, i think that vmware supports nested virt.  To be clear?  i don't actually need a TPM to get this setup with KVM/QEMU right?

**Comment by nabilschear** [comment]
ok, i finally got this up and running and played around with it a bit.  it looks like the main things we'd need to do are:

- add deepquote support to https://github.com/stefanberger/libtpms . Hopefully not too terribly hard, and we can use Xen implementation as a guide: https://github.com/mirage/xen/commit/f00b68e706c052002fbcbe820f434f1f1afb725d . the challenge here will be how to exernalize what swtpm should do upon receiving a deepquote.  would it execute the tpm2-tools quote operation manually?  call keylime node (running on the host) to do it for it?
- build a version of deepquote into https://github.com/tpm2-software/tpm2-tools . again we can use https://github.com/keylime/tpm4720-keylime/blob/master/libtpm/lib/pcrs.c as a start.
- need to move swtpm's temporary state into /var/lib/keylime or some other tmpfs place
- need to see if the guest kernel will pass the deepquote ord or if it will balk at it.

**Comment by lukehinds** [comment]
well done, I was literally just working on a VM to give you.

That list sounds quite extensive or is that a case of it being new to me makes it sound more complex than it is? Are these tasks you can take on @nabilschear , I am totally willing to help, but will be honest, I would not know where to begin just yet.

Initial thoughts:

I expect for adding deepquote to libtpms, we would need to first raise a github issue and thrash out the details of the implementation with stefan.

for the deepquote into tpm2-tools, the folks upstream at tpm2-software were quite helpful in helping us land charlies patches there, so this should be doable.

move swtpm's temporary state into /var/lib/keylime or some other tmpfs place - is this a case of when running `swtpm socket` set the path as ` /var/lib/keylime/tpm0/` or the like?

**Comment by lukehinds** [comment]
@nabilschear @jetwhiz upstream discussion point: https://github.com/stefanberger/swtpm/issues/145

**Comment by ozoder** [comment]
I've been playing with Keylime using vTPM in KVM/QEMU a little bit and I have a few observations I want to share.

When it comes to TPM 1.2, it seems that Keylime works properly without any additional changes. I also tried to use tmpfs mounted in /var/lib/keylime for the swtpm socket and I didn't run into any problems. This is how to use the tmpfs:
```
mount -t tmpfs -o size=10m,mode=0700 tmpfs /var/lib/keylime/
swtpm socket --tpmstate dir=/var/lib/keylime/ --ctrl type=unixio,path=/var/lib/keylime/swtpm-sock &
```

However, when I tried TPM 2.0, the Keylime agent didn't initialize properly (tpm2.tpm_init function failed). The vTPM itself seems to be mostly working (commands like tpm2_getrandom and tpm2_pcrlist for example). 

This is the output I got when running the agent:
```
Using config file /etc/keylime.conf
2019-08-27 18:40:31.827 - keylime.tpm2 - INFO - Using legacy version of tpm2-tools
2019-08-27 18:40:31.924 - keylime.secure_mount - INFO - mounting secure storage location /var/lib/keylime/secure on tmpfs
2019-08-27 18:40:31.950 - keylime.tpm - WARNING - INSECURE: Keylime is using a software TPM emulator rather than a real hardware TPM.
2019-08-27 18:40:31.953 - keylime.tpm - WARNING - INSECURE: The security of Keylime is NOT linked to a hardware root of trust.
2019-08-27 18:40:31.954 - keylime.tpm - WARNING - INSECURE: Only use Keylime in this mode for testing or debugging purposes.
2019-08-27 18:40:31.956 - keylime.tpm2 - INFO - Taking ownership with config provided TPM owner password: keylime
2019-08-27 18:40:31.970 - keylime.tpm2 - INFO - TPM Owner password confirmed: keylime
Traceback (most recent call last):
  File "/usr/bin/keylime_agent", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_agent')()
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/cloud_agent.py", line 481, in main
    (ek,ekcert,aik,ek_tpm,aik_name) = tpm.tpm_init(self_activate=False,config_pw=config.get('cloud_agent','tpm_ownerpassword')) # this tells initialize not to self activate the AIK
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tpm2.py", line 796, in tpm_init
    ekcert = self.read_ekcert_nvram()
  File "/usr/lib/python2.7/site-packages/keylime-1.2-py2.7.egg/keylime/tpm2.py", line 1065, in read_ekcert_nvram
    raise Exception("tpm2_nvread for ekcert failed with code "+str(code)+": "+str(output))
Exception: tpm2_nvread for ekcert failed with code 1: ['ERROR: Failed to read NVRAM area at index 0x1c00002 (29360130). Error:0x9a2\n', 'ERROR: Unable to run tpm2_nvread\n']
```

I looked a little bit deeper and found out that most of the commands in tpm2.tpm_init like tpm2_takeownership, tpm2_getcap, tpm2_readpublic, and tpm2_nvlist execute properly, but it fails on tpm2_nvread, specifically with these arguments:
```
tpm2_nvread -x 0x1c00002 -s 1065 -f /tmp/tmpk0Qf3h
```
Any ideas why this might be happening?

One note that might be important - I was communicating directly with the TPM instead of using tpm2-abrmd.

If you want to try this out for yourself, you can use the [setup script](https://gist.github.com/lukehinds/9fcee6fdc451d44116086b13b6125db9) by Luke. I've adjusted it for my needs a little, but it's almost the same. I'll upload my script later.

**Comment by mrcdb** [comment]
Hi @ozoder . The error code results in an authorization failure when retrieving the NV index of the EK cert. Is the EK cert available under storage or platform hierarchy ? Can you check the NV index attributes via `tpm2_nvlist` ?

Also, I would like to add that I am doing some tests with TPM 2.0 simulator in these days, that I installed through the Keylime installer. In my case, there is no EK cert available at `0x1c00002`, and I had to create one myself.

**Comment by lukehinds** [comment]
hi @ozoder , give it a try with `require_ek = False`

**Comment by ozoder** [comment]
After some time I got back to the vTPM testing and this time everything worked properly. I'm not sure what exactly happened since the last time I was testing this, but hopefully this means that we can run Keylime within a QEMU/KVM virtual machine with the vTPM state inside a mounted tmpfs drive.

I've created pull request [#192](https://github.com/keylime/keylime/pull/192) with the script I used to set up a virtual machine.

**Comment by ferdinan4** [comment]
Hi guys!

I am sorry to bother you, but I am quite confuse! . I am starting to use the swtpm because I wanna to make it works properly. I would describe my starting point because maybe the architecture that I am using it is not correct.

I have a VMs with Fedora (running over VMWare WorkStation). There I have already install the swtpm (https://github.com/stefanberger/swtpm).

It is properly installed (because it passed some intallation test and some basic command is working properly).

Now start the problems ....

1-.I dont know where I can find documentation about the project (No wiki) for last version in GitHub.
2.- I dont know which TSS can I use to make it compatible with that version of SW-tpm
3.- I need to move to Qemu-kvm instead of VMware? 
4.-What it is libtpms exactly?

Sorry for this noob's questions but I started with this project las week.

Regards,

Fernando

**Comment by lukehinds** [comment]
hi @ferdinan4 

No such thing as noob questions! There are a lot of aspects to the project, so ask away anything you like, whenever you're curious. 

Is it specifically the vTPM would like to get working or you would just like to have Keylime work within a VM? If you would like to play with Keylime and set up a test / development environment, I would recommend the main TPM emulator (which is different to the vTPM).

Let me know which option you wish to proceed with and I can support you getting it in place.

Also welcome to the project, great to have you here.

Luke

**Comment by lukehinds** [comment]
Also if it suits you, we meet at [15:00 UTC](https://time.is/mg/1500%20UTC) every Wednesday on our [gitter channel](https://gitter.im/keylime-project/community)

**Comment by ferdinan4** [comment]
Hi @lukehinds !

Thanks for your response.

To be honest I would like to work with vTPM, and understand all the architecture that there are under it.

I was following your chat and I found **vtpm-setup.sh** under fedora OS.

So I decided to install it, but when I try to run the Virtual machine created it isn´t work. I guess it is because I am trying to launch a VM over another VM (my Linux Fedora).
This is the error that appears:
`root password is : XXXXXXXXXXXXx
Installing test
**WARNING  KVM acceleration not available, using 'qemu'**

Starting install...
Domain creation completed.
Injecting tpm2 to libvirt xml
Domain 'test' defined successfully.
Changes will take effect after the domain is fully powered off.
Reboot for changes to take effect
**error: Unknown mode test value, expecting 'acpi', 'agent', 'initctl', 'signal' or 'paravirt'**

To login to the vm run: virsh console test
Please then complete the following steps:
# dhclient should get an address for the vm
# dnf install tpm2-tools tpm2-tss tpm2-abrmd
Then run the abrmd as root:
# /usr/sbin/tpm2-abrmd --allow-root &
You should now be able to query the tpm with a command such as tpm2_pcrlist
`

Yeah, I think I can connect to the channel!

Thanks you for your response!

Fernando

**Comment by lukehinds** [comment]
Adding as a 6.0 milestone feature.

**Comment by nullr0ute** [comment]
Ultimately as it already supports a general TPM2 to spec it should just work whatever the underlying TPM2 is.

**Comment by THS-on** [comment]
> Ultimately as it already supports a general TPM2 to spec it should just work whatever the underlying TPM2 is.

Yes using a virtualized/emulated TPM like swtpm or Ken's TPM emulator just works fine with Keylime.

This issue is about vTPM support with deep quotes like it is in Xen supported for TPM 1.2.  Deep quotes are not part of the TPM2 spec and were never implemented outside of Xen.
